on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      TESTCOVERAGE_THRESHOLD: 70
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - if: matrix.os == 'windows-latest'
        run:
          go test -v -cover ./...
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

